name: jiji
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.9.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  hexcolor: ^1.0.4
  intro_slider: ^2.3.3
  otp_text_field:
  pin_code_text_field: ^1.7.1
  dio: ^3.0.10
  share: ^0.6.5+2
  image_picker: ^0.6.7+11
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  path_provider: ^1.6.18
  provider: ^4.3.2+2
  flutter_svg: ^0.19.0
  flutter_native_image: ^0.0.5
  cached_network_image: ^2.3.2+1
  fluttertoast: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.2+1
  build_runner: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/